# Generated by Django 2.2.1 on 2019-05-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMTNews_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_subscribed',
            new_name='is_subscribed',
        ),
    ]
