# Generated by Django 2.2.1 on 2019-05-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BMTNews_App', '0002_auto_20190523_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_text', models.TextField()),
                ('news_img', models.ImageField(upload_to='media/')),
                ('news_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
