# Generated by Django 2.2.1 on 2019-06-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMTNews_App', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
